//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        [Required]
        public int FeedbackId { get; set; }
        [Required]
        public int UserId { get; set; }
        [Required]
        public int Correctness { get; set; }
        [Required]
        public int Safety { get; set; }
        [Required]
        public int Rate_of_Service { get; set; }
        [Required]

        public virtual User User { get; set; }
    }
}
