//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PassengerBooking
    {
        [Required]
        public int PassengerBookingId { get; set; }
        [Required]
        public int UserId { get; set; }
        [Required]
        public int ShipId { get; set; }
        [Required]
        public Nullable<int> Tickets_Available { get; set; }
        [Required]
        public double TicketCost { get; set; }
        [Required]
        public int NoOfTickets { get; set; }
        [Required]
        public double TotalPrice { get; set; }
        [Required]
        public System.DateTime BookingDate { get; set; }
     
        public virtual Ship Ship { get; set; }
        public virtual User User { get; set; }
    }
}
