//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship()
        {
            this.CargoBookings = new HashSet<CargoBooking>();
            this.PassengerBookings = new HashSet<PassengerBooking>();
        }
        [Required]
        public int ShipId { get; set; }
        [Required]
        public int ShipNumber { get; set; }
        [Required]
        public string ShipModel { get; set; }
        [Required]
        public string ShipType { get; set; }
        [Required]
        public string FacilityType { get; set; }
        [Required]
        public string Source { get; set; }
        [Required]
        public string Destination { get; set; }
        [Required]
        public System.DateTime DepartureDate { get; set; }
        [Required]
        public System.TimeSpan DepartureTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoBooking> CargoBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerBooking> PassengerBookings { get; set; }
    }
}
