//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShipAccount
    {
        [Required]
        public int ShipAccountId { get; set; }
        [Required]
        public int AccountNumber { get; set; }
        [Required]
        public Nullable<decimal> AccountBalance { get; set; }
    }
}
